name: Deploy Next.js site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: 'next-app' # Specify the subdirectory path

      # ... Other steps such as detecting package manager, setting up Node, installing dependencies, building Next.js, etc.

      - name: Static HTML export with Next.js
        run: |
          cd next-app
          # Export static HTML with Next.js here

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: next-app-output
          path: next-app/out

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: next-app-output
          path: next-app/out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          provider: pages
          path: next-app/out # Specify the subdirectory for deployment
