name: Deploy Next.js site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: 'next-app' # Specify the subdirectory path

      - name: Detect package manager
        id: detect-package-manager
        run: |
          cd next-app # Change directory before running commands
          # Add your package manager detection logic here, considering the new path

      - name: Setup Node
        run: |
          cd next-app # Change directory before running commands
          # Setup Node here, considering the new path

      # Adjust other steps in a similar manner
