name: Deploy Next.js site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # with:
        #   path: 'next-app' # Specify the subdirectory path

      # ... Other steps such as detecting package manager, setting up Node, installing dependencies, building Next.js, etc.

      - name: Static HTML export with Next.js
        run: |
          cd next-app
          ls
          npm install # Install dependencies if needed
          npm run build # Build your Next.js app (if not already built)
          # npm run export # Export static HTML with Next.js

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: next-app-output # Adjust the artifact name as needed
          path: next-app/out # Adjust the path to where the artifact is generated

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: next-app-output # Ensure this matches the artifact name from the build job
          path: next-app/out # Adjust the path to retrieve the artifact

      - name: Deploy to GitHub Pages
        # uses: actions/deploy-pages@v2
        # with:
        #   token: ${{ secrets.GITHUB_TOKEN }}
        #   artifact_name: next-app-output # Ensure this matches the uploaded artifact name
        run: |
          cd next-app/out  # Navigate to the artifact directory
          find * -type l    # List symbolic links
          find . -type l    # List symbolic links
          
