name: Deploy Next.js site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Static HTML export with Next.js
        run: |
          cd next-app
          ls
          npm install # Install dependencies if needed
          npm run build # Build your Next.js app (if not already built)

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          name: next-app-output # Adjust the artifact name as needed
          path: next-app/out # Adjust the path to where the artifact is generated
          
      - name: Test artifact
        run: |
          ls
          cd next-app/out
          ls
          ls _next

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: next-app-output # Ensure this matches the artifact name from the build job
          path: next-app/out # Adjust the path to retrieve the artifact
          
      - name: Artifact test
        run: |
          ls next-app/out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.MY_TOKEN }}
          source_dir: next-app/out/_next # Adjust this path to point directly to _next
          artifact_name: next-app-output # Ensure this matches the uploaded artifact name
